services:
  - type: web
    name: taxiq-app
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
